[ssh] fixes __parse_cez_hostname()

diff --git a/bin/ssh_cez b/bin/ssh_cez
--- a/bin/ssh_cez
+++ b/bin/ssh_cez
@@ -33,21 +33,19 @@ function __test_parse_cez_hostname() {
 }
 
 function __parse_cez_hostname() {
-    setopt local_options BASH_REMATCH
-
     local cez_hostname="${1}"
     local regex="^(n-)?([a-z0-9]{3,7})([a-z0-9]{2})(-[a-z0-9]{2,3})?$"
 
-    if ! [[ "${cez_hostname}" =~ "${regex}" ]]; then
+    if ! [[ "${cez_hostname}" =~ ${regex} ]]; then
         >&2 ansi --red "no match"
 
         return 1
     fi
 
-    local prefix="${BASH_REMATCH[2]}"
-    local sid="${BASH_REMATCH[3]}"
-    local role="${BASH_REMATCH[4]}"
-    local suffix="${BASH_REMATCH[5]}"
+    local prefix="${BASH_REMATCH[1]}"
+    local sid="${BASH_REMATCH[2]}"
+    local role="${BASH_REMATCH[3]}"
+    local suffix="${BASH_REMATCH[4]}"
 
     echo "${prefix}:${sid}:${role}:${suffix}"
 }
@@ -70,9 +68,11 @@ function ssh_cez() {
                 cez_hostname="${2}"
                 cez_commands="${3}"
 
-                local parsed="$(__parse_cez_hostname "${2}")"
+                local parsed
+                local sid
 
-                local sid="$(echo "${parsed}" | cut -d: -f2)" || {  # TODO: doesn't catch error
+                parsed="$(__parse_cez_hostname "${2}")"
+                sid="$(echo "${parsed}" | cut -d: -f2)" || {  # TODO: doesn't catch error
                     >&2 echo
                     >&2 ansi --bold --red "Cannot parse SID."
 
