Moves theme palette colors from tmux module to separate folder.

diff --git a/bin/tmux_set_theme b/bin/tmux_set_theme
--- a/bin/tmux_set_theme
+++ b/bin/tmux_set_theme
@@ -9,6 +9,7 @@ date +"%d.%m.%Y %H:%M:%S - ${CALLER}"
 
 export DOTFILES_ROOT="${HOME}/.dotfiles"
 export DOTFILES_LIBS_ROOT="${DOTFILES_ROOT}/libs"
+export DOTFILES_THEMES_ROOT="${DOTFILES_ROOT}/themes"
 
 # load libraries
 echo "› loading libraries"
@@ -32,16 +33,6 @@ if ! tmux info &> /dev/null; then
     exit 0
 fi
 
-# in case color palette is not found, set a horrible one to notice
-tmux_theme_bg="#ff0000"
-tmux_theme_fg="#ffffff"
-tmux_theme_box_bg="#000000"
-tmux_theme_box_fg="#ffffff"
-tmux_theme_box_current_bg="#00ff00"
-tmux_theme_box_current_fg="#000000"
-tmux_theme_box_utils_bg="#0000ff"
-tmux_theme_box_utils_fg="#ffffff"
-
 tmux_theme_name="light"
 
 case "${DOTFILES_OS}" in
@@ -62,46 +53,49 @@ if [[ "${tmux_theme_cached_name}" == "${tmux_theme_name}" ]]; then
     exit 0
 fi
 
-tmux_theme_source_file="${HOME}/.tmux/conf/themes/palette.${tmux_theme_name}.conf"
+# load theme colors
+echo "› loading theme colors"
 
-if [[ -r "${tmux_theme_source_file}" ]]; then
-    source "${tmux_theme_source_file}"
-
+if load_theme_colors; then
     echo "Setting theme to ${tmux_theme_name}."
 else
     tmux_theme_name="broken"
 
-    >&2 echo "Can't read theme file '${tmux_theme_source_file}'. Setting broken theme."
+    >&2 echo "Loading theme color failed. Setting broken theme."
 fi
 
 echo -n "${tmux_theme_name}" > "${tmux_theme_cache_location}"
 
+
+
+# ___ set tmux colors, style & formats ________________________________________
+
 # set selection and buffer scrollbar foreground and background
-tmux set -g mode-style "fg=${tmux_theme_box_utils_fg} bg=${tmux_theme_box_utils_bg}"
+tmux set -g mode-style "fg=${DOTFILES_THEME_TERTIARY_FG} bg=${DOTFILES_THEME_TERTIARY_BG}"
 
 # set message bar's foreground and background
-tmux set -g message-style "fg=${tmux_theme_box_utils_fg} bg=${tmux_theme_box_utils_bg}"
+tmux set -g message-style "fg=${DOTFILES_THEME_TERTIARY_FG} bg=${DOTFILES_THEME_TERTIARY_BG}"
 
 # set the status bar's foreground and background
-tmux set -g status-fg "${tmux_theme_fg}"
-tmux set -g status-bg "${tmux_theme_bg}"
+tmux set -g status-fg "${DOTFILES_THEME_FG}"
+tmux set -g status-bg "${DOTFILES_THEME_BG}"
 
 # set the left and right status
-tmux set -g status-left "#[bg=${tmux_theme_box_utils_bg},fg=${tmux_theme_box_utils_fg}] #S #[bg=${tmux_theme_bg}] " # session name (eg: 0)
-tmux set -g status-right " #[bg=${tmux_theme_box_utils_bg},fg=${tmux_theme_box_utils_fg}] continuum: #{continuum_status} #[bg=${tmux_theme_bg}] #[bg=${tmux_theme_box_utils_bg},fg=${tmux_theme_box_utils_fg}] %d.%m.%Y %R #[bg=${tmux_theme_bg}] #[bg=${tmux_theme_box_utils_bg},fg=${tmux_theme_box_utils_fg}] #H " # continuum period + datetime + hostname
+tmux set -g status-left "#[bg=${DOTFILES_THEME_TERTIARY_BG},fg=${DOTFILES_THEME_TERTIARY_FG}] #S #[bg=${DOTFILES_THEME_BG}] " # session name (eg: 0)
+tmux set -g status-right " #[bg=${DOTFILES_THEME_TERTIARY_BG},fg=${DOTFILES_THEME_TERTIARY_FG}] continuum: #{continuum_status} #[bg=${DOTFILES_THEME_BG}] #[bg=${DOTFILES_THEME_TERTIARY_BG},fg=${DOTFILES_THEME_TERTIARY_FG}] %d.%m.%Y %R #[bg=${DOTFILES_THEME_BG}] #[bg=${DOTFILES_THEME_TERTIARY_BG},fg=${DOTFILES_THEME_TERTIARY_FG}] #H " # continuum period + datetime + hostname
 
 # set window status format
-tmux set -g window-status-current-format "#[bg=${tmux_theme_box_current_bg},fg=${tmux_theme_box_current_fg}] #I #W #{?window_zoomed_flag,[zoomed] ,}" # window index + name (eg: 1 git)
-tmux set -g window-status-format "#[bg=${tmux_theme_box_bg},fg=${tmux_theme_box_fg}] #I #W " # window index + name (eg: 1 git)
+tmux set -g window-status-current-format "#[bg=${DOTFILES_THEME_PRIMARY_BG},fg=${DOTFILES_THEME_PRIMARY_FG}] #I #W #{?window_zoomed_flag,[zoomed] ,}" # window index + name (eg: 1 git)
+tmux set -g window-status-format "#[bg=${DOTFILES_THEME_SECONDARY_BG},fg=${DOTFILES_THEME_SECONDARY_FG}] #I #W " # window index + name (eg: 1 git)
 
 # set pane border format
-tmux set -g pane-border-format "#[fg=${tmux_theme_box_current_fg}]#P: #T (#H)" # pane number + pane title (eg: 1: dev (host.local))
+tmux set -g pane-border-format "#[fg=${DOTFILES_THEME_PRIMARY_FG}]#P: #T (#H)" # pane number + pane title (eg: 1: dev (host.local))
 
 # make pane border
-tmux set -g pane-border-style "fg=${tmux_theme_box_bg} bg=${tmux_theme_box_bg}"
+tmux set -g pane-border-style "fg=${DOTFILES_THEME_SECONDARY_BG} bg=${DOTFILES_THEME_SECONDARY_BG}"
 
 # make active pane border
-tmux set -g pane-active-border-style "fg=${tmux_theme_box_current_bg} bg=${tmux_theme_box_current_bg}"
+tmux set -g pane-active-border-style "fg=${DOTFILES_THEME_PRIMARY_BG} bg=${DOTFILES_THEME_PRIMARY_BG}"
 
 # initialize TMUX plugin manager (keep this line at the very bottom of any tmux conf, that is ran on its own)
 tmux run -b '~/.tmux/plugins/tpm/tpm'
